# New build process workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Linting
        run: echo linting job placeholder

      - name: Build and Publish
        run: echo build job placeholder

      - name: Trigger Central Repository Build
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.CENTRAL_PAT }}
          repository: brianpatrickreavey/repository.kodi.reavey05.com
          event-type: addon-release
          client-payload: '{"addon": "${{ github.repository }}", "tag": "${{ github.ref_name }}"}'